# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - forgesheets

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install django==5.0.3
          pip install psycopg2-binary==2.9.9
          pip install whitenoise==6.6.0
          pip install gunicorn==21.2.0
          pip install python-dotenv==1.0.1
          pip list


        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Cleaning testing files
        run: |
          cd ForgeSheets/
          rm .env
          cd ..

      - name: Zip artifact for deployment
        run: |
          cd ForgeSheets/
          zip release.zip ./* -r
          cd ..
          mv ForgeSheets/release.zip .
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D95D1F8086CB4EB2B7D273D02527E16D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9108D82907E0487BA8A3C1802AC7E34F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_51F4AE8D04EF4E4D9A3A0E584EF77DB3 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'forgesheets'
          slot-name: 'Production'
